config/routes.rb
Rails.application.routes.draw do
  get 'login', to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  get "user/:profile_page", to: "users#show"

  root "main#index"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :username, presence: true,
                       uniqueness: { scope: :email }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: VALID_EMAIL_REGEX }

  validates :profile_page, presence: true,
                           uniqueness: true

  def to_param
    profile_page
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to root_path unless logged_in?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authorized

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      flash[:alert] ? "" : ""
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Incorrect email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:alert] = "You've been logged out"
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
require "aws-sdk-s3"

class SongsController < ApplicationController
  def index;# feed page
  end

  def new
    @song = Song.new
  end

  # current_user's page
  def collection
    @user = User.where(profile_page: params[:profile_page]).first
    @songs = Song.where(user_id: @user.id)
  end

  def create
    if !params[:song][:file_path].content_type.include?("audio")
      flash[:alert] = "Please upload an audio file"
      return
    end

    response = upload(params[:song][:file_path], params[:song][:name])
    if response.successful?
      params[:song][:file_path] = create_file_path(params[:song][:name])
      @song = Song.new(song_params)

      if @song.save
        flash[:notice] = "Song #{params[:song][:name]} has been uploaded!"
        redirect_to root_path
      else
        render :new
      end
    else
      flash[:notice] = "There was an error uploading #{params[:song][:name]}. Please try again."
      render :new
    end
  end

  def play
    current_song = params[:song]
  end

  private
  def song_params
    params.require(:song).permit(:file_path, :name, :user_id)
  end

  R2_ENDPOINT = "https://#{Rails.application.credentials.dig(:cloudflare, :account_id)}.r2.cloudflarestorage.com".freeze
  SONGS_BUCKET = 'amp-songs'.freeze

  def s3_client
    Aws::S3::Client.new(
      access_key_id: Rails.application.credentials.dig(:cloudflare, :access_key_id),
      secret_access_key: Rails.application.credentials.dig(:cloudflare, :secret_access_key),
      endpoint: R2_ENDPOINT,
      region: "auto"
    )
  end

  def song_path(file)
    R2_ENDPOINT + "/" + file
  end

  def upload(file, name)
    s3 = s3_client
    resp = ""

    File.open(file, 'rb') do |f|                     # Needs to be something unique to user (i.e. profile_page)
      resp = s3.put_object(bucket: SONGS_BUCKET, key: create_file_path(name), body: f)
    end
    resp
  end

  def create_file_path(name)
    params[:song][:file_path] = "users/#{current_user.profile_page}/#{name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :authorized, only: %i[ new create ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show;
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to root_path unless current_user == @user
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find_by_profile_page(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :username, :profile_page, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  R2_ENDPOINT = "https://#{Rails.application.credentials.dig(:cloudflare, :account_id)}.r2.cloudflarestorage.com".freeze

  def download_song(song_path)
    resp = s3_client.get_object(bucket: "amp-songs", key: song_path)
    resp
  end

  def s3_client
    Aws::S3::Client.new(
      access_key_id: Rails.application.credentials.dig(:cloudflare, :access_key_id),
      secret_access_key: Rails.application.credentials.dig(:cloudflare, :secret_access_key),
      endpoint: R2_ENDPOINT,
      region: "auto"
    )
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title publicmusic.org
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = favicon_link_tag asset_path('favicon.ico')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %main
      %div
        = render "shared/nav"
        = yield

        - if Rails.env.development?
          = render "shared/dev_tool"

app/views/main/index.html.haml
-# %h1.text-blue-800 amp: another music platform

app/views/shared/_audio_player.html.haml
%div.absolute.bottom-0.w-full.bg-blue-400.flex.items-center.py-5{ data: { controller: "audio-player", "audio_player_hide_class": "hidden" } }
  %audio{ id: "audio-player"}
  %div.inline-flex.items-center.ml-16{ id: "audio-controls" }
    %button{ id: "back" }
      = material_icon.shape(:skip_previous).md_48.style('color: white')
    %button{ id: "audio-player-play", data:{ "audio_player_target": "play", action: "click->audio-player#play" }}
      = material_icon.shape(:play_circle).md_48.style('color: white')
    %button.hidden{ id: "audio-player-pause", data: { "audio_player_target": "pause", action: "click->audio-player#pause" }}
      = material_icon.shape(:pause_circle).md_48.style('color: white')
    %button{ id: "next" }
      = material_icon.shape(:skip_next).md_48.style('color: white')
    %p.ml-8.text-white.text-xl{ id: "audio-player-song-title" }

app/views/shared/_dev_tool.html.haml
#dev-widget-bar
  %span #{controller_path}##{action_name}
  %span.join= "|"
  %span.dev-label Rails Version:
  %span= Rails::VERSION::STRING
  %span.join= "|"
  %span.dev-label Ruby Version:
  %span= RUBY_VERSION

%style
  :plain
    #dev-widget-bar {
      position: fixed;
      bottom: 0;
      right: 0;
      background-color: black;
      color: #ccc;
      padding: 4px 10px;
      font: 14px Lato, sans-serif;
      cursor: pointer;
      z-index: 2147483647;
    }

    #dev-widget-bar .dev-label {
      color: #999;
    }

    #dev-widget-bar .join {
      color: #999;
      padding: 0 10px;
    }

app/views/shared/_flash.html.haml
- if flash[:notice]
  %div
    = flash[:notice]

- if flash[:alert]
  %div
    = flash[:alert]

app/views/shared/_nav.html.haml
%div.w-full.bg-blue-400.flex.items-center.py-6
  %div.inline-flex
    %div.font-sans.ml-10.text-2xl.text-white= link_to "public|music|dot|org", root_path
  %div.w-full.flex-grow.lg-flex.lg.inset-y-0.right-0
  - if logged_in?
    %div.font-sans.text-l.text-white.mr-8= link_to "Upload", root_path
    %div.font-sans.text-l.text-white.mr-8= link_to "#{current_user.username}", user_path(current_user), method: :get
    %div.font-sans.text-l.text-white.mr-8= button_to "Logout", logout_path, method: :delete
  - else
    %div.font-sans.text-l.text-white.mr-8.whitespace-nowrap= link_to "Sign Up", sign_up_path
    %div.font-sans.text-l.text-white.mr-8= link_to "Login", login_path

app/views/songs/_song.html.haml
%div{ data: { controller: "song", "song-id-value": "#{song.id}", "song-path-value": "#{song.file_path}", "song-playback-url-value": "#{Rails.application.credentials.dig(:cloudflare, :amp_songs_endpoint)}", "song_hide_class": "hidden", "song-title-value": song.name }}
  %div.pt-4{ data: {action: "click->song#load"} }
    %div.pl-8.flex.items-center{ id: song.id }
      %div.cursor-pointer{ data: {"song_target": "play"}, id: "#{song.id}-play-icon" }
        = material_icon.shape(:play_circle).md_48.style('color: #60A5FA')
      %div.cursor-pointer.hidden{ data: { "song_target": "pause" }, id: "#{song.id}-pause-icon" }
        = material_icon.shape(:pause_circle).md_48.style('color: #60A5FA')
      %div.pl-4 #{song.name}

app/views/songs/_upload_form.html.haml
%div.w-full.max-w-xs
  = form_with model: @song, url: upload_path, data: { turbo: false },   class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |f|
    - if @song.errors.any?
      %div
        %ul
        - user.errors.full_messages.each do |msg|
          %li= msg
    %div.mb-4
      = f.label :name, class: "block text-gray-700 text-sm font-bold mb-2"
      = f.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

    %div.mb-4
      = f.label :file, class: "block text-gray-700 text-sm font-bold mb-2"
      = f.file_field :file_path, direct_upload: true, class: "appearance-none rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

      = f.hidden_field :user_id, value: current_user.id

    %div.flex.items-center.justify-between
      = f.submit "Upload", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
  %p.text-center.text-gray-500.text-xs public music org

app/views/songs/collection.html.haml
%h2 #{@user.profile_page}'s Collection
%div
  - @songs.each do |song|
    = render partial: "song", locals: { song: song }

app/views/songs/index.html.haml
%div Songs!

app/views/songs/new.html.haml
%div.mx-auto.md-w-2.w-full
  = render "upload_form", user: @song

app/views/users/_form.html.haml
-# locals: (path:, user:)

%div.w-full.max-w-xs
  = form_with model: user, url: path, data: { turbo: false }, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |f|
    %div.mb-4
      = f.label :name, class: "block text-gray-700 text-sm font-bold mb-2"
      - if user.errors.messages[:name].any?
        = f.text_field :name, class: "shadow appearance-none appearance-none border-2 border-red-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        %div.text-red-500.bold= user.errors.messages[:name].first
      - else
        = f.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

    %div.mb-6
      = f.label :username, class: "block text-gray-700 text-sm font-bold mb-2"
      - if user.errors.messages[:username].any?
        = f.text_field :username, class: "shadow appearance-none appearance-none border-2 border-red-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        %div.text-red-400= user.errors.messages[:username].first
      - else
        = f.text_field :username, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

    %div.mb-6
      = f.label :email, class: "block text-gray-700 text-sm font-bold mb-2"
      - if user.errors.messages[:email].any?
        = f.text_field :email, class: "shadow appearance-none border-2 border-red-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        %div.text-red-400= user.errors.messages[:email].first
      - else
        = f.text_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

    %div.mb-6
      = f.label :profile_page, class: "block text-gray-700 text-sm font-bold mb-2"
      - if user.errors.messages[:profile_page].any?
        = f.text_field :profile_page, class: "shadow appearance-none border-2 border-red-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        %div.text-red-400= user.errors.messages[:profile_page].first
      - else
        = f.text_field :profile_page, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

    %div.mb-6
      = f.label :password, class: "block text-gray-700 text-sm font-bold mb-2"
      - if user.errors.messages[:password].any?
        = f.password_field :password, class: "shadow appearance-none border-2 border-red-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        %div.text-red-400= user.errors.messages[:password].first
      - else
        = f.password_field :password, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

    %div.mb-6
      = f.label :password_confirmation, class: "block text-gray-700 text-sm font-bold mb-2"
      - if user.errors.messages[:password_confirmation].any?
        = f.password_field :password_confirmation, class: "shadow appearance-none border-2 border-red-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        %div.text-red-400= user.errors.messages[:password_confirmation].first
      - else
        = f.password_field :password_confirmation, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

    %div.flex.items-center.justify-between
      - if user.new_record?
        = f.submit "Sign Up", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
      - else
        = f.submit "Confirm Changes", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-5 rounded focus:outline-none focus:shadow-outline"
        = link_to "Cancel", user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium"

  %p.text-center.text-gray-500.text-xs public music dot org

app/views/users/_user.html.haml
%div{:id => "#{dom_id user}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Name:
    = user.name
  %p.my-5
    %strong.block.font-medium.mb-1 Username:
    = user.username
  %p.my-5
    %strong.block.font-medium.mb-1 Email:
    = user.email
  %p.my-5
    %strong.block.font-medium.mb-1 Profile page:
    = user.profile_page
  - if action_name != "show"
    = link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to 'Edit this user', edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6

app/views/users/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing user
  = render "form", path: user_path(@user), user: @user

app/views/users/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl Users
    = link_to 'New user', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #users.min-w-full
    = render @users

app/views/users/new.html.haml
%div.mx-auto.md-w-2.w-full
  = render "form", user: @user, path: users_path

app/views/users/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @user
    = link_to 'Edit Profile', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"